### ISSUE TITLE
Flash Esphome

### ISSUE THREAD

**Issue by pengemetal** [cybertza/PAI-ESP32#2]
Hi,

Please help me! How can I flash ESP? I used HA ESP add-on, alarmstreamer.yaml is ok, I can see it on my LAN, but how can I flash main.cpp? Do I need to use Platformio or change main.cpp file in Esphome library? Pai add-on can not connect to ESP, I think lack of Telnet. Thanks in advance!

**Comment by cybertza** [comment]
You can use either, what port are you trying to connect to?

**Comment by pengemetal** [comment]
23
![Screenshot_20211231_063109_io homeassistant companion android](https://user-images.githubusercontent.com/56131015/147805348-7c3a73b7-867e-4371-839d-3af110a0cf6d.jpg)
![Screenshot_20211231_063236_io homeassistant companion android](https://user-images.githubusercontent.com/56131015/147805349-fcef1f4f-b3f4-49f1-8e25-9b0830f2695f.jpg)

**Comment by pengemetal** [comment]
I sketched main.cpp with Arduino and PAI can connect to telnet! But how can I use it with esphome? Thx

**Comment by pengemetal** [comment]
I find the solution: I was confused and I forgot to add port number in esphome yaml

**Comment by sparkydave1981** [comment]
I hate to try and revive this but the instructions for how to flash a device to use with PAI are extremely limited.

I would like to flash an ESP32 using the ESPhome method.  What exactly do I need to flash and where?  I mean, do we only need to flash via the ESPhome add-on or do we need to do something else?  Is it possible to elaborate on the wiki instructions please?

**Comment by cybertza** [comment]
Just follow the guide on how to flash esphome onto a device from their website.

You will need a basic understanding of esphome to use this implementation. 

Mine has been running for so long the yaml is maybe outdated.

But this is just an easy way to create a wifi to serial bridge for very cheap.

**Comment by sparkydave1981** [comment]
> You will need a basic understanding of esphome

I've got plenty of experience with ESPhome, I've been using it before it called ESPhome.  The thing is, the instructions for this implementation aren't clear as to if we do all of it in ESPhome or whatever.

the main.cpp file has reference to wifi details etc.  Do we need to edit that as well as the ESPhome file? or are the settings in the ESPhome config file enough?

**Comment by cybertza** [comment]
Yea, ok. I understand the mixup.

It's 2 different implementations: one is compiled, other is just esp home.

**Comment by sparkydave1981** [comment]
> Yea, ok. I understand the mixup.
> 
> It's 2 different implementations: one is compiled, other is just esp home.

ok, sooooo, what is the full process to get the ESPhome based version onto the device?

**Comment by cybertza** [comment]
Yea just create a news device on esphome as basic, then add the yaml text in there.

Check for relevance on changes of ota or whatever. 

It just uses an implementation of serial code, so it's just the yaml.
